language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm run coverage
  - npm run semantic-release
after_failure: npm run coverage
