language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
