flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: api-test
        type: project
        target: auto
        threshold: 2%
      - name_prefix: e2e-test
        type: project
        target: auto
        threshold: 2%
      - name_prefix: unit-test-
        type: project
        target: auto
        threshold: 2%
      - name_prefix: api-test
        type: patch
        target: 70%
      - name_prefix: e2e-test
        type: patch
        target: 70%
      - name_prefix: unit-test-
        type: patch
        target: 70%