comment:
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 5%
      # - name_prefix: patch-
      #   type: patch
      #   target: 70%