comment:
  show_carryforward_flags: true

# Setting coverage targets per flag
coverage:
  default_rules:
    carryforward: true
    threshold: 5%
    target: auto
  status:
    project:
      default:
        target: 80% #overall project/ repo coverage
      api-tests:
        flags:
          - api-test
      unit-test-server:
        flags:
          - unit-test-server
      unit-test-client:
        flags:
          - unit-test-client
      unit-test-achievements:
        flags:
          - unit-test-achievements
