/**
 * @file Automatically generated by barrelsby.
 */

export * from './get-all.decorator';
export * from './get-one.decorator';
export * from './kb-api-validation-error-response.decorator';
export * from './kb-delete.decorator';
export * from './kb-patch.decorator';
export * from './kb-post.decorator';
export * from './kb-put.decorator';
