name: Add PR Deploy Badge
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]

jobs:
  badge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    steps:
    - name: TEST KB-BADGER-ACTION
      uses: kibibit/kb-badger-action@v1.91
      with:
        style: for-the-badge
        github-token: ${{secrets.GITHUB_TOKEN}}
        badge-left: demo
        badge-right: application
        badge-logo: heroku
        badge-path: api
        badge2-left: demo
        badge2-right: api--docs
        badge2-color: 85EA2D
        badge2-logo: swagger
        badge2-path: api/docs
