name: API Tests
on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'server/**'
  push:
    branches:
      - master
      - next
jobs:
  unittest:
    name: API Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Install Dependencies
        run: |
          npm ci
          npm install
      - name: Build
        run: npm run build --if-present
      - name: Run API Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run test:api
      - name: Archive test results & coverage
        uses: actions/upload-artifact@v2
        with:
          name: server-unit-tests-code-coverage-report
          path: test-results/api