name: "Build"

on:
  pull_request:
  push:
    branches: 
      - master
      - next

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npm install
          npm run build