name: Server Unit Tests
on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'server/**'
  push:
    paths:
    - 'server/**'

jobs:
  serverunittest:
    name: Server Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: |
          npm ci
          npm install
      - name: Build
        run: npm run build --if-present
      - name: Run Server Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run test:server-unit
      - name: Archive test results & coverage
        uses: actions/upload-artifact@v2
        with:
          name: server-unit-tests-code-coverage-report
          path: test-results/server
      # - name: Code Coverage Report
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: coverage/server/lcov.info